In [53]:
import numpy as np

np.random.seed(42)

# Matrice aléatoire : entier, flottant , normale ..
matr0 = np.random.randint( 1,11, size = (4, 4))
matr1 = np.random.randint( 1,11, size = (4, 4))
matr2 = np.random.randint( 11,21, size = (4, 4))

print(matr0,'\n\n', matr1, '\n\n',matr2, '\n\n', matr0.shape)

[[ 7  4  8  5]
 [ 7 10  3  7]
 [ 8  5  4  8]
 [ 8  3  6  5]] 

 [[ 2  8  6  2]
 [ 5  1 10  6]
 [ 9  1 10  3]
 [ 7  4  9  3]] 

 [[15 13 17 15]
 [19 17 12 14]
 [19 12 20 19]
 [20 15 12 14]] 

 (4, 4)


In [54]:
#Empilement horizontal
print(np.hstack([matr0, matr1, matr2]).shape)

#Empilement vertical
print(np.vstack([matr0, matr1, matr2]).shape)

(4, 12)
(12, 4)


In [63]:
#Ajout d'un axe à nos matrices
matr0_ = np.expand_dims(matr0, -1)
matr1_ = np.expand_dims(matr1, -1)
matr2_ = np.expand_dims(matr2, -1)
print("On passe d'une dimension : "+str(matr0.shape)+" à une dimension "+ str(matr0_.shape)+"\n\n")

# Accès au premier nombre
print(matr0_[0,0,0])


#Ajout d'une 
new_matr = np.array([matr0_, matr1_, matr2_])
print(new_matr.shape)

new_matr_bis = np.array([matr0_, matr1_, matr2_], axis = -1)
print(new_matr_bsi.shape)

new_matr_ = new_matr.squeeze(-1)
print(new_matr_.shape)

print(new_matr_)

print(new_matr_[2,0,0])
print(new_matr_[2,:,:])
print(new_matr_[2,:,:].shape)

On passe d'une dimension : (4, 4) à une dimension (4, 4, 1)


7
(3, 4, 4, 1)


TypeError: array() got an unexpected keyword argument 'axis'

In [48]:
x = np.array([[[1,1,2], [2,3,3]], [[1,1,1], [1,1,1]]])
print(x.shape)
print(x)


(2, 2, 3)
[[[1 1 2]
  [2 3 3]]

 [[1 1 1]
  [1 1 1]]]


In [3]:
matr.reshape(2,8)
print(matr)

[[ 2  1  1  4]
 [ 7  5 10  6]
 [ 5  8  7 10]
 [ 5  3  1 10]]


### L'objet n'est pas modifié !!

In [7]:
print(matr.shape)
matr2 = matr.reshape(2,8)
print(matr2)
print(matr2.shape)

(4, 4)
[[ 2  1  1  4  7  5 10  6]
 [ 5  8  7 10  5  3  1 10]]
(2, 8)


### Autre  forme d'appel 

In [5]:
matr3 = np.reshape(matr, (2,8))
print(matr3)

[[ 3 10  1  3  7  3  9  5]
 [ 3  2  5  2  7  1  4  8]]


### Autre constructeur

In [18]:
matr = np.arange(2,26,2)
print(matr)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [19]:
print(matr.shape)


(12,)


### Prendre note de la notation (nb,)

In [20]:
matr2 = matr.reshape(3,4)
print(matr2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


#### Obtenir des informations

In [42]:
print(matr.dtype, matr.itemsize, matr.size,matr.ndim )

print(matr2.size, matr2.ndim)


int32 4 12 1
12 2


In [22]:
print(len(matr))
print(len(matr2))

12
3


#### Autre notation

In [40]:
matr2 = np.reshape(matr, (3,4))
print(matr2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [43]:
# Matrice
print(matr2, 'shape', matr2.shape)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]] shape (3, 4)


In [44]:
# vecteur colonne
matr3 = matr2.reshape(-1,1)
print(matr3, 'shape', matr3.shape)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]] shape (12, 1)


In [45]:
# vecteur ligne
matr3 = matr2.reshape(1,-1)
print(matr3, 'shape', matr3.shape)

[[ 2  4  6  8 10 12 14 16 18 20 22 24]] shape (1, 12)


In [47]:
#liste
print(matr, 'shape', matr.shape)

[ 2  4  6  8 10 12 14 16 18 20 22 24] shape (12,)
